@extends('errors.layout')
@section('code', '500')
@section('icon', '⚙️')
@section('title', 'เกิดข้อผิดพลาดในระบบ')
@section('message', 'เกิดข้อผิดพลาดที่ไม่คาดคิด ทีมงานได้รับแจ้งแล้ว กรุณาลองใหม่อีกครั้งในอีกสักครู่')
